import { Montserrat,Kanit } from "next/font/google";
import "../globals.css";
import SessionWrapper from "../../components/SessionWrapper";
import Nav from "@/components/shop/Nav";

const mont = Montserrat({ subsets: ["latin"] });
const protest = Kanit({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-protest",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body
          className={`${mont.className} ${protest.variable}  bg-blue-200 w-screen h-[100vh] overflow-hidden container mx-auto`}
        >
          <Nav />
          {children}
        </body>
      </html>
    </SessionWrapper>
  );
}
